#ifndef MEOWLLOC_CONFIG_H
#define MEOWLLOC_CONFIG_H



#ifndef MEOWLLOC_CONFIG_PAGESIZE
#define MEOWLLOC_CONFIG_PAGESIZE (4096)
#endif

#ifndef MEOWLLOC_CONFIG_ARENASIZE
#define MEOWLLOC_CONFIG_ARENASIZE (4096)
#endif

#ifndef MEOWLLOC_CONFIG_ALIGNMENT
#define MEOWLLOC_CONFIG_ALIGNMENT (alignof(max_align_t))
#endif



#endif // MEOWLLOC_CONFIG_H
